In [ ]:
import numpy as np

In [ ]:
M_matriz = np.array([2,3,4,5,6,7,8,9,1]).reshape(3,3)
M_matriz

array([[2, 3, 4],
       [5, 6, 7],
       [8, 9, 1]])

In [ ]:
L_matriz = np.array([1,2,3,4,5,6,7,8,9,]).reshape(3,3)
L_matriz

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
N = L_matriz @ M_matriz
N

array([[ 36,  42,  21],
       [ 81,  96,  57],
       [126, 150,  93]])

In [ ]:
np.linalg.det(N)

6.906475391588151e-12