In [136]:
import numpy as np

class Examen():
    def __init__(self):
      print("PARCIAL 1")

In [137]:
examen = Examen()

PARCIAL 1


In [138]:
class Triangulo(Examen):

      def __init__(self):
        Examen.__init__(self)
        print("Clase heredada: Triangulo")

      def area_equilatero(self):
          l = int(input("Ingrese el largo de un lado de un triángulo equilatero: "))
          h = ((l*np.sqrt(3))/2)
          a = ((l*2*np.sqrt(3))/4)
          print("El área del triángulo es: ", a)

      def perimetro_equilatero(self):
          l = int(input("Ingrese el largo de un lado de un triángulo equilatero: "))
          p = l*3
          print("El perímetro del triángulo es: ", p)

In [139]:
triangulo = Triangulo()

PARCIAL 1
Clase heredada: Triangulo


In [140]:
triangulo.area_equilatero()

Ingrese el largo de un lado de un triángulo equilatero: 3
El área del triángulo es:  2.598076211353316


In [141]:
triangulo.perimetro_equilatero()

Ingrese el largo de un lado de un triángulo equilatero: 3
El perímetro del triángulo es:  9


In [142]:
class Matriz(Examen):

    def __init__(self):
        Examen.__init__(self)
        print("Clase heredada: Matriz")

    def matriz(self, lista):
        print(np.array(lista).reshape(4, 4))

    def determinante(self, A):
        print(np.linalg.det(A))

class TransformarMatriz:
    def __init__(self, lista):
        self.lista = lista

    def transformar(self):
        return np.array(self.lista).reshape(4, 4)

class CalcularDeterminante:
    def __init__(self, matriz):
      Examen.__init__(self)
      self.matriz = matriz

    def determinante(self):
      print(np.linalg.det(matriz))

In [143]:
matriz = Matriz()

PARCIAL 1
Clase heredada: Matriz


In [144]:
lista = [i for i in range(1, 17)]
transformador = TransformarMatriz(lista)
matriz = transformador.transformar()
print("Matriz 4x4: ")
print(matriz)

Matriz 4x4: 
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [145]:
calculador = CalcularDeterminante(matriz)
determinante = calculador.determinante()
print("Determinante: ", determinante)

PARCIAL 1
0.0
Determinante:  None
